# Generated by Django 5.0.3 on 2024-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_barber_managers_remove_barber_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='name',
        ),
    ]
