# Generated by Django 5.0.3 on 2024-07-30 12:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='haircut_type',
            new_name='service_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='haircut',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 13, 18, 1, 71327, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Haircut',
            new_name='Service',
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.service')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(through='playground.AppointmentService', to='playground.service'),
        ),
    ]
