# Generated by Django 5.0.3 on 2024-04-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_alter_barber_first_name_alter_barber_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barber',
            options={'ordering': ['id', 'username', 'email', 'first_name', 'last_name', 'bio', 'experience_years', 'is_available', 'service_menu', 'booking_preferences', 'location', 'specialization']},
        ),
    ]
