# Generated by Django 5.0.3 on 2024-07-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_rename_haircut_type_review_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BarberService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.barber')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.service')),
            ],
            options={
                'unique_together': {('barber', 'service')},
            },
        ),
    ]
