# Generated by Django 5.0.3 on 2024-04-30 16:32

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_barber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='Default Location', max_length=63),
        ),
    ]
