# Generated by Django 5.0.3 on 2024-08-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_appointment_services_alter_appointment_barber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barbers', to='playground.service'),
        ),
    ]
